/**
 * action-types.js
 */

//root
export const SET_LOADING = "SET_LOADING";

// auth
export const LOGIN_ACTION = "LOGIN_ACTION";
export const LOGOUT_ACTION = "LOGOUT_ACTION";
export const LOGIN_SUCCESS = "LOGIN_SUCESS";
export const LOGOUT_SUCCESS = "LOGOUT_SUCCESS";
export const LOGIN_ERROR = "LOGIN_ERROR";
export const LOGOUT_ERROR = "LOGOUT_ERROR";
export const RESET_AUTH = "RESET_AUTH";

// course
export const GET_COURSE_ACTION = "GET_COURSE_ACTION";
export const COURSE_REFRESHING = 'COURSE_REFRESHING';
export const COURSE_REFRESHING_NO_DATA = 'COURSE_REFRESHING_NO_DATA';
export const COURSE_LOADING = 'COURSE_LOADING';
export const COURSE_LOADING_NO_DATA = 'COURSE_LOADING_NO_DATA';
export const GET_COURSE_SUCCESS = 'GET_COURSE_SUCCESS';
export const GET_COURSE_FAIL = 'GET_COURSE_FAIL';
export const GET_MORE_COURSE_SUCCESS = 'GET_MORE_COURSE_SUCCESS';
export const GET_MORE_COURSE_FAIL = 'GET_MORE_COURSE_FAIL';

export const GET_COURSE_DETAIL_ACTION = "GET_COURSE_DETAIL_ACTION";
export const GET_COURSE_DETAIL_SUCCESS = "GET_COURSE_DETAIL_SUCCESS";
export const GET_COURSE_DETAIL_FAIL = "GET_COURSE_DETAIL_FAIL";

export const ADD_COURSE_ACTION = "ADD_COURSE_ACTION";
export const ADD_COURSE_SUCCESS = "ADD_COURSE_SUCCESS";
export const ADD_COURSE_FAIL = "ADD_COURSE_FAIL";

export const EDIT_COURSE_ACTION = "EDIT_COURSE_ACTION";
export const EDIT_COURSE_SUCCESS = "EDIT_COURSE_SUCCESS";
export const EDIT_COURSE_FAIL = "EDIT_COURSE_FAIL";

export const DELETE_COURSE_ACTION = "DELETE_COURSE_ACTION";
export const DELETE_COURSE_SUCCESS = "DELETE_COURSE_SUCCESS";
export const DELETE_COURSE_FAIL = "DELETE_COURSE_FAIL";

export const RESET_COURSE = "RESET_COURSE";
export const SET_COURSE = "SET_COURSE";

export const RESET_COURSE_RESPONSE = "RESET_COURSE_RESPONSE";
export const SET_COURSE_RESPONSE = "SET_COURSE_RESPONSE";


